# Site settings
title: Abhishek's Tech Dojo
header-img: img/saturn-bg.jpg
email: abhishes@gmail.com
copyright_name: Your/Project/Corporate Name
description: ""
baseurl: ""
url: "/"
twitter_username: abhishes
github_username:  abhsrivastava
facebook_username:  
email_username:  abhishes@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 50
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
